---
title: "Fundamentals of Computational Mathematics - Homework 13"
author: "Jered Ataky"
date: "4/24/2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



$$

1.\ Integrate\ \int 4e^{-7x} dx\\
\\
Let\ u\ =\ -7x\ \Longrightarrow \ dx\ =\ -\frac{du}{7}\\
\\
We\ have:\int 4e^{-7x} dx\ =\ 4\int \frac{e^{u}}{-7} du\ =\ -\frac{4}{7} e^{u} \ +\ c\ =\ -\frac{4}{7} e^{-7x} +\ C\\
\\
\\

$$

$$
2.\ Rate\ of\ change\ and\ estimation\ function.\\
\\
\frac{dN}{dt} =-\frac{3150}{t^{4}} -220\\
\\
dN\ =\left( \ -\frac{3150}{t^{4}} -220\right) dt\\
\\
N\ =\ \int \left( \ -\frac{3150}{t^{4}} -220\right) dt\\
\\
N\ =\ \frac{1050}{t^{3}} -220t\ +\ C\\
N( 1) \ =\ 6530\ \Longrightarrow \ 6530\ =\ 1050-220+C\\
\Longrightarrow \ C\ =\ 5700\\
\\
Therefore,\ N( t) \ =\ \ \frac{1050}{t^{3}} -220t\ +\ 5700\\
\\
\\
\\

$$

$$
3.\ Area\ of\ red\ recatngle:\\
\\
f( x) \ =\ 2x-9\\
\\
The\ line\ is\ bounded\ at\ x\ =\ 4.5\ and\ x\ =\ 8.5\\
\\
Let\ find\ the\ area:\\
\\
Area\ =\ \int _{4.5}^{8.5}( 2x-9) dx\ =\ x^{2} \ -\ 9x\ |\ x\ =\ 4.5,\ 8.5\\
\\
=\ \left( 8.5^{2} -9( 8.5)\right) -\left( 4.5^{2} -9( 4.5)\right)\\
\\
=\ -4.25-( -20.25) \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\
\\
=\ -4.25+20.25\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\
\\
=\ 16\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\
\\
\\

$$

4. Area under the curve


Plotting the two functions...

```{r}

f1 <- function(x) x^2 - 2*x - 2

f2 <- function(x) x + 2

x1 <- seq(-1.5, 6, 1)

plot(x1, f1(x1), type ='l', col='blue', xlab = "", ylab = "")
lines(x1, f2(x1), col='red')
abline(h=0)

```




$$
y\ =\ x^{2} -2x-2,\ y\ =\ x+2\\
\\
Findind\ the\ area\ boundaries:\ x^{2} -2x-2\ =\ x+2\\
\Longrightarrow \ x^{2} -3x-4\ =0\ \Longrightarrow \ x\ =\ -1,\ x=4\\
\\
Area\ =\ \int _{-1}^{4}\left(( x+2) -\left( x^{2} -2x-2\right)\right) dx\\
\\
=\ \int _{-1}^{4}\left( -x^{2} +3x+4\right) dx\ =\ -\frac{x^{3}}{3} +\frac{3}{2} x^{2} +4x\ |x=-1,\ 4\\
=\ \left( -\frac{64}{3} +24+16\right) -\left(\frac{1}{3} +\frac{3}{2} -4\right)\\
=\ \frac{56}{3} +\frac{13}{6}\\
\\
=\ \frac{112+13}{6}\\
\\
=\frac{125}{6}\\
\\
\\

$$



$$
5.\ \ Minimize\ the\ cost\\
\\
We\ know\ that:\ Total\ cost\ =\ fixed\ cost\ +\ variable\ cost\\
\\
Let\ x\ be\ number\ of\ order\\
\\
fixed\ cost\ =8.25x\\
\\
Variable\ cost\ is\ function\ of\ lot\ size\ as\ well.\\
\\
lot\ size\ =s\ =\ \frac{total\ of\ irons\ sold}{number\ of\ order}\\
\\
Thus,\ s\ =\ \frac{110}{x}\\
\\
Cost\ over\ the\ year\ \Longrightarrow \ uniform\ distribution\ of\ lot\ size,\ s\ =\ s/2:\\
\\
We\ can\ define\ the\ total\ cost\ function:\ C( x) \ =\ 8.25x\ +\ 3.75\left(\frac{\frac{110}{x}}{2}\right)\\
\\
\Longrightarrow \ C( x) \ =\ 8.25x\ +\ \frac{206.25}{x}\\
\\
First\ derivative\ to\ minimize\ the\ cost:\ C'( x) \ =\ 8.25-\frac{206.25}{x^{2}}\\
C'( x) \ =\ 0\ \Longrightarrow \ x^{2} \ =\ \frac{206.25}{8.25} \ \Longrightarrow \ x\ =\ 5\\
\\
x\ =\ 5\ \Longrightarrow \ s\ =\ \frac{110}{5} =22\\
\\
\\
The\ lot\ size\ and\ the\ number\ of\ orders\ per\ year\ that\ will\ minimize\ inventory\ costs\\
\\
are\ respectively\ 22\ and\ 5.\ \\
\\
$$





$$
6.\ Integrate\ \ by\ parts:\ \int ln( 9x) x^{6} dx\\
\\
We\ know\ that:\ \int udv\ =\ uv-\int vdu\\
\\
du\ =\ x^{6} dx\ \Longrightarrow \ u\ =\int x^{6} dx\ \Longrightarrow \ u\ =\ \frac{x^{7}}{7}\\
v\ =\ ln( 9x) \ \Longrightarrow \ dv\ =\frac{1}{x} dx\\
\\
So:\ \int ln( 9x) x^{6} dx\ =\int vdu\ \ =uv-\int udv=\left(\frac{x^{7}}{7}\right)( ln( 9x) -\int \frac{x^{7}}{7}\left(\frac{1}{x}\right) dx\\
\\
=\ \frac{1}{7} x^{7} ln( 9x) -\frac{1}{7}\int x^{6} dx\\
\\
=\ \ \frac{1}{7} x^{7} ln( 9x) -\frac{1}{7}\left(\frac{x^{7}}{7}\right) \ +\ C\\
\\
=\ \ \ \frac{1}{7} x^{7} ln( 9x) -\frac{1}{49} x^{7} +C\\
\\
\\
\\

$$




$$
7.\ Probability\ function\\
\\
We\ need\ to\ verify\ if\ \int _{1}^{e^{6}} f( x) dx\ =\ 1.\\
\\
\\
We\ have:\ \int _{1}^{e^{6}} f( x) dx\ \ =\ \int _{1}^{e^{6}}\frac{1}{6x} dx\ =\ \frac{1}{6} ln( x) \ |\ x\ =1,\ e^{6}\\
\\
=\ \frac{1}{6} ln\left( e^{6}\right) -\frac{1}{6} ln( 1)\\
\\
=1-0\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\
\\
=\ 1\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\
\\
\\
\\
Since\ \ \int _{1}^{e^{6}} f( x) dx\ =\ 1,\ we\ can\ \ conclude\ that\ \ f( \ x\ ) \ is\ a\ probability\ density\ function\ \\
on\ the\ interval\ \left[ 1,\ e^{6} \ \right]\\
\ \ \ \ \ \ \ \ \ \ \ \ \\
\\
$$






