---
title: "Fundamentals of Computational Mathematics - Homework 15"
author: "Jered Ataky"
date: "5/15/2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pracma)
library(MASS)

```


## Question 1

```{r}

# Define the response

y <- c(8.8, 12.4, 14.8, 18.2, 20.8)

# Explanatory variable

x <- c(5.6, 6.3, 7, 7.7, 8.4)

lm1 <- lm(y~x)
summary(lm1)
```


**The equation of the line is: y = -14.80 + 4.26x**



## Question 2

$$
f( x,y) \ =\ 24x-6xy^{2} -8y^{3}\\
\\
*\ f_{x}( x,y) \ =\ 24-6y^{2} ;\ f_{x}( x,y) =0\Longrightarrow \ y\ =\ 2\ \ or\ \ y\ =\ -2\\
*f_{y}( x,y) \ =\ -12xy-24y^{2} ;\ f_{y}( x,y) \ =\ 0\Longrightarrow \ x\ =\ -2y.\\
\\
for\ y=2,\ x=-4,\ f( -4,\ 2) \ =\ -64\ \Longrightarrow \ P_{1} =( -4,\ 2,\ -64)\\
\ for\ y\ =\ -2,\ x\ =\ 4,\ f( 4,-2) =64\Longrightarrow \ P_{2} =( 4,\ -2,\ 64)\\
\\
\\
Critical\ points\ are\ P_{1} =( -4,\ 2,\ -64) \ and\ \ P_{2} =( 4,\ -2,\ 64)\\
\\
*\ The\ second\ derivative\ test:\\
\\
f_{xx}( x,y) \ =\ 0\\
\\
f_{yy}( x,y) =-12x-48y;\ f_{yy}( -4,\ 2) =-48;\ f( 4,-2) =48\\
\\
f_{xy}( x,y) =-12y;\ f( -4,2) =-24;\ f( 4,-2) \ =\ 24\\
\\
We\ can\ see\ that\ D( -4,\ 2) \ =\ D( 4,\ -2) \ =\ 0-( 24)^{2} =-576< 0\\
\\
\\
\Longrightarrow \ The\ critical\ points\ are\ saddle\ points.
$$



## Question 3

Step1: The revenue function

$$
Revenue\ for\ house:\ R( x,y) =( 81-21x+17y) x\\
Revenue\ for\ name:\ R( x,y) =( 40+11x-23y) y\\
\\
1.\ Total\ revenue\ function:\\
\\
R( x,y) \ =\ ( 81-21x+17y) x+( 40+11x-23y) y\\
\Longrightarrow R( x,y) =81x-21x^{2} +17xy+40y+11xy-23y^{2}\\
\\
\Longrightarrow R( x,y) =-21x^{2} -23y^{2} +81x+40y+28xy

$$


Step2: Calculating the revenue

```{r}

f <- function(x,y) {-21*x^2 - 23*y^2 + 81*x +40*y + 28*x*y}

paste0("The revenue will be $", f(2.30, 4.10))


```






## Question 4


$$
C( x,y) =\frac{1}{6} x^{2} +\frac{1}{6} y^{2} +7x+25y+700\\
\\
constraint:\ x+y=96\Longrightarrow \ y\ =\ 96-x\\
\\
C( x,y) =\frac{1}{6} x^{2} +\frac{1}{6}( 96-x)^{2} +7x+25( 96-x) +700\\
\\
C_{x} =\frac{1}{3} x-\frac{1}{3}( 96-x) +3( 7-25)\\
C_{x} =0\Longrightarrow \ 2x=150\ \Longrightarrow \ x=75\\
y\ =\ 96-75\ \Longrightarrow \ y\ =21\\
\\
\\
\\
To\ mininize\ the\ total\ weekly\ cost,\ the\ plant\ should\ produce\ 75\ units\ in\ Los\ Angeles\\
and\ 21\ units\ in\ Denver.

$$ 




## Question 5

$$
\iint _{R}\left( e^{8x+3y}\right) dA;\ R:\ 2\leqslant x\leqslant 4\ and\ 2\leqslant y\leqslant 4\\
\\
=\ \int _{2}^{4}\int _{2}^{4}\left( e^{8x+3x}\right) dxdy=\int _{2}^{4}\int _{2}^{4} e^{8x} e^{3y} dxdy\\
\\
=\ \int _{2}^{4} e^{8x} dx\ \int _{2}^{4} e^{3y} dy\ =\ \left[\frac{e^{32} -e^{16}}{8}\right]\left[\frac{e^{12} -e^{6}}{3}\right]\\
\\
=\frac{1}{24}\left( e^{32} -e^{16}\right)\left( e^{12} -e^{6}\right)

$$ 








