---
title: "Fundamentals of Computational Mathematics - Homework 4"
author: "Jered Ataky"
date: "2/15/2021"
output:
  pdf_document: default
  html_document:
    number_sections: yes
  openintro::lab_report: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = normalizePath("C:/Jered_Files/images_rest/jpg"))
memory.size(max=T)
```


## Libraries

```{r}

library(doParallel)
library(foreach)
library(jpeg)
library(kableExtra)
library(OpenImageR)


setwd("C:/Jered_Files/images/jpg")
```


```{r}
library(EBImage)

```



## Use of Graphics


```{r}
num=20
#files=list.files("D:/FootJoy/Images/jpg",pattern="\\.jpg")[1:num] 

files=list.files("C:/Jered_Files/images/jpg",pattern="\\.jpg")[1:num]

```


## View Shoes Functions


```{r}

height=1200; width=2500;scale=20
plot_jpeg = function(path, add=FALSE)
{ jpg = readJPEG(path, native=T) # read the file
  res = dim(jpg)[2:1] # get the resolution, [x, y]
  if (!add) # initialize an empty plot area if add==FALSE
    plot(1,1,xlim=c(1,res[1]),ylim=c(1,res[2]),asp=1,type='n',xaxs='i',yaxs='i',xaxt='n',yaxt='n',xlab='',ylab='',bty='n')
  rasterImage(jpg,1,1,res[1],res[2])
}

```

## Load the Data into an Array


```{r}

im=array(rep(0,length(files)*height/scale*width/scale*3), dim=c(length(files), height/scale, width/scale,3))

for (i in 1:20){
  temp=resize(readJPEG(paste0("C:/Jered_Files/images/jpg", files[i])),height/scale, width/scale)
  im[i,,,]=array(temp,dim=c(1, height/scale, width/scale,3))}

```


## Vectorize

```{r}

flat=matrix(0, 20, prod(dim(im))) 
for (i in 1:20) {
  newim <- readJPEG(paste0("C:/Jered_Files/images/jpg", files[i]))
  r=as.vector(im[i,,,1]); g=as.vector(im[i,,,2]);b=as.vector(im[i,,,3])
  flat[i,] <- t(c(r, g, b))
}
shoes=as.data.frame(t(flat))

```


## Actual Plots

```{r}

par(mfrow=c(3,3))
par(mai=c(.3,.3,.3,.3))
for (i in 1:20){  #plot the first images only
plot_jpeg(writeJPEG(im[i,,,]))
}


```

### Get eigencompents for correlation structure


```{r}

scaled=scale(shoes, center = TRUE, scale = TRUE)
mean.shoe=attr(scaled, "scaled:center") #saving for classification
std.shoe=attr(scaled, "scaled:scale")  #saving for classification...later

```


## Calculate Covariance (Correlation)

```{r}

Sigma_=cor(scaled)


```

## Get eigencomponents

```{r}

myeigen=eigen(Sigma_)
cumsum(myeigen$values) / sum(myeigen$values)

```

## Eigenshoes


```{r}

scaling=diag(myeigen$values[1:5]^(-1/2)) / (sqrt(nrow(scaled)-1))
eigenshoes=scaled%*%myeigen$vectors[,1:5]%*%scaling
imageShow(array(eigenshoes[,1], c(60,125,3)))


```


## Generate Principal Components


```{r}

height=1200
width=2500
scale=20
newdata=im
dim(newdata)=c(length(files),height*width*3/scale^2)
mypca=princomp(t(as.matrix(newdata)), scores=TRUE, cor=TRUE)


```


## Generate eigneshoes

```{r}

mypca2=t(mypca$scores)
dim(mypca2)=c(length(files),height/scale,width/scale,3)
par(mfrow=c(5,5))
par(mai=c(.001,.001,.001,.001))
for (i in 1:20){#plot the first 25 Eigenshoes only
plot_jpeg(writeJPEG(mypca2[i,,,], bg="white"))  #complete without reduction
}



```


### Variance capture


```{r}

a=round(mypca$sdev[1:20]^2/ sum(mypca$sdev^2),3)
cumsum(a)


```


## New data set

```{r}
x = t(t(eigenshoes)%*%scaled)

```


